name: KaituoSurvivalProps
version: '1.0'
main: fun.kaituo.kaituoSurvivalProps.KaituoSurvivalProps
api-version: '1.21'
authors: [ APairOfMoons ]

commands:
  getsizepotion:
    description: Gives a potion that can change your size

  getbreaker:
    description: Gives a block breaker

  getinfinitefood:
    description: Gives food that will not be consumed

  getlabitem:
    description: Gives the specified lab item

permissions:
  kaituoprops.*:
    description: Parent permission for kaituoprops

    children:
      kaituoprops.getsizepotion:
        description: Permission to use /getsizepotion command
        default: op

      kaituoprops.getbreaker:
        description: Permission to use /getbreaker command
        default: op

      kaituoprops.getinfinitefood:
        description: Permission to use /getinfinitefood command
        default: op